# Linear Regression

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('simDTS.csv')
new_data = data.groupby(['t']).agg(number = ('t','count'),dr=('y','sum'),edr=('pd','sum'),std = ('pd','std'))
data["dr"] = new_data["dr"]/new_data["number"]
data['c'] = data['v'] + data['t']
#data = pd.read_csv('src/visualization/simDTS.csv')

In [3]:
data

Unnamed: 0     key   t  v   x1  x2        h1        x4  del  y  \
0                 1       1   1  2  619   0 -0.100923 -0.031003    0  0   
1            100001       1   2  2  619   0  0.498312 -0.123908    0  0   
2            200001       1   3  2  619   0 -0.733160  0.572345    0  0   
3            300001       1   4  2  619   0 -0.343541  0.529761    0  0   
4            399992       1   5  2  619   0  3.113732  0.659377    0  0   
...             ...     ...  .. ..  ...  ..       ...       ...  ... ..   
2383337     1988830  100000  20  7  651   0 -2.077314  0.096079    0  0   
2383338     2087523  100000  21  7  651   0 -1.606836  0.106994    0  0   
2383339     2186171  100000  22  7  651   0 -0.553857  0.045785    0  0   
2383340     2284777  100000  23  7  651   0 -0.380921  0.125809    0  0   
2383341     2383342  100000  24  7  651   0 -0.722160 -0.039230    0  0   

                   pd       dr   c  
0        1.381276e-09      NaN   3  
1        9.396210e-07  0.00000   4  
2        1.638122e-05  0.00000   5  
3        6.487583e-05  0.00009   6  
4        1.278584e-04  0.00034   7  
...               ...      ...  ..  
2383337  4.487481e-05      NaN  27  
2383338  4.091167e-05      NaN  28  
2383339  3.677615e-05      NaN  29  
2383340  3.252146e-05      NaN  30  
2383341  2.822985e-05      NaN  31  

[2383342 rows x 13 columns]

In [5]:
from sklearn import model_selection
#x_train, x_test = model_selection.train_test_split(xList, test_size=0.2) 
#y_train, y_test = model_selection.train_test_split(data['x4'], test_size=0.2) 
train, test = model_selection.train_test_split(data, test_size=0.2) 
#print(train)

In [6]:
#train._get_value(1126070, 't')
print(test)

         Unnamed: 0    key   t   v   x1  x2        h1        x4  del  y  \
936001       339295  39295   4  12  653   0  0.380589  0.764318    0  0   
843871      1132977  35432  12  17  738   0  1.764422  0.045785    0  0   
71374       1100793   3000  12  28  629   0  2.010588 -0.248250    0  0   
376663       715409  15823   8  27  632   0  6.346462 -0.156558    0  0   
372238      2004232  15634  21   2  559   0 -6.105488  0.601214    0  0   
...             ...    ...  ..  ..  ...  ..       ...       ...  ... ..   
376473      1708040  15814  18  35  523   0 -3.132937 -0.102316    0  0   
1461657     1950621  61346  20  30  548   0 -2.264886 -0.260986    0  0   
1689539     1762498  70908  18  16  570   0 -3.952597 -0.047057    0  0   
1261744     1744746  52963  18  23  635   0  7.375566 -0.330212    0  0   
70314       1100748   2955  12  27  618   0  0.110343 -0.158014    0  0   

               pd  dr   c  
936001   0.000026 NaN  16  
843871   0.000007 NaN  29  
71374    0.0001

In [7]:

from operator import index


xTrain = []
for i in train.index:
    d = []
    d.append(train._get_value(i, 't'))
    #d.append(train['t'][i])
    d.append(train._get_value(i, 'v'))
    #d.append(train['v'][i])
    d.append(train._get_value(i, 'c'))
    xTrain.append(d)




xTest = []
for i in test.index:
    d = []
    d.append(test._get_value(i, 't'))
    #d.append(test['t'][i])
    d.append(test._get_value(i, 'v'))
    #d.append(test['v'][i])
    d.append(test._get_value(i, 'c'))
    xTest.append(d)


#yTrain = train['dr']
#yTest = test['dr']
yTrain = train['pd']
yTest = test['pd']

print(len(xTrain),len(xTest),len(yTrain),len(yTest))

1906673 476669 1906673 476669


### linear regression with no normalization

In [8]:
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(xTrain,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=xTest,y=yTest))
err = reg.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

[-6868.35325592 -6868.35325742  6868.35325789] 0.0005806863992903505
0.00010213902426203791
0.001594608261078973


### linear regression with regularization

###### alpha=1

In [9]:
from sklearn.linear_model import Ridge
clf1 = Ridge(alpha=1)
clf1.fit(xTrain,yTrain)
print(clf1.coef_,clf1.intercept_)

print(clf1.score(X=xTest,y=yTest))
err1 = clf1.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[ 1.15534804e-06 -3.39802583e-07  8.15544770e-07] 0.0005807117763182069
0.00010212148247501496
0.0015946082750665407


###### alpha=10000

In [10]:
from sklearn.linear_model import Ridge
clf2 = Ridge(alpha=999)
clf2.fit(xTrain,yTrain)
print(clf2.coef_,clf2.intercept_)

print(clf2.score(X=xTest,y=yTest))
err2 = clf2.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err2**2)))

[ 1.15533881e-06 -3.39797442e-07  8.15541371e-07] 0.0005807119023953452
0.00010212142250587419
0.0015946082751143594


### one hot encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#### integer encoding

In [19]:
label_encoder = LabelEncoder()
data['t_encode'] = label_encoder.fit_transform(data['t'])
print(data['t_encode'])
data['v_encode']  = label_encoder.fit_transform(data['v'])
print(data['v_encode'])
data['c_encode']  = label_encoder.fit_transform(data['c'])
print(data['c_encode'])

0           0
1           1
2           2
3           3
4           4
           ..
2383337    19
2383338    20
2383339    21
2383340    22
2383341    23
Name: t_encode, Length: 2383342, dtype: int64
0          1
1          1
2          1
3          1
4          1
          ..
2383337    6
2383338    6
2383339    6
2383340    6
2383341    6
Name: v_encode, Length: 2383342, dtype: int64
0           1
1           2
2           3
3           4
4           5
           ..
2383337    25
2383338    26
2383339    27
2383340    28
2383341    29
Name: c_encode, Length: 2383342, dtype: int64


In [20]:
train_encode, test_encode = model_selection.train_test_split(data, test_size=0.2) 
data

Unnamed: 0     key   t  v   x1  x2        h1        x4  del  y  \
0                 1       1   1  2  619   0 -0.100923 -0.031003    0  0   
1            100001       1   2  2  619   0  0.498312 -0.123908    0  0   
2            200001       1   3  2  619   0 -0.733160  0.572345    0  0   
3            300001       1   4  2  619   0 -0.343541  0.529761    0  0   
4            399992       1   5  2  619   0  3.113732  0.659377    0  0   
...             ...     ...  .. ..  ...  ..       ...       ...  ... ..   
2383337     1988830  100000  20  7  651   0 -2.077314  0.096079    0  0   
2383338     2087523  100000  21  7  651   0 -1.606836  0.106994    0  0   
2383339     2186171  100000  22  7  651   0 -0.553857  0.045785    0  0   
2383340     2284777  100000  23  7  651   0 -0.380921  0.125809    0  0   
2383341     2383342  100000  24  7  651   0 -0.722160 -0.039230    0  0   

                   pd       dr   c  t_encode  v_encode  c_encode  
0        1.381276e-09      NaN   3         0         1         1  
1        9.396210e-07  0.00000   4         1         1         2  
2        1.638122e-05  0.00000   5         2         1         3  
3        6.487583e-05  0.00009   6         3         1         4  
4        1.278584e-04  0.00034   7         4         1         5  
...               ...      ...  ..       ...       ...       ...  
2383337  4.487481e-05      NaN  27        19         6        25  
2383338  4.091167e-05      NaN  28        20         6        26  
2383339  3.677615e-05      NaN  29        21         6        27  
2383340  3.252146e-05      NaN  30        22         6        28  
2383341  2.822985e-05      NaN  31        23         6        29  

[2383342 rows x 16 columns]

In [22]:
from operator import index


xTrain_encode = []
for i in train_encode.index:
    d = []
    d.append(train_encode._get_value(i, 't'))
    #d.append(train['t'][i])
    d.append(train_encode._get_value(i, 'v'))
    #d.append(train['v'][i])
    d.append(train_encode._get_value(i, 'c'))
    xTrain_encode.append(d)




xTest_encode = []
for i in test_encode.index:
    d = []
    d.append(test_encode._get_value(i, 't'))
    #d.append(test['t'][i])
    d.append(test_encode._get_value(i, 'v'))
    #d.append(test['v'][i])
    d.append(test_encode._get_value(i, 'c'))
    xTest_encode.append(d)


#yTrain = train['dr']
#yTest = test['dr']
#same as before
#yTrain = train['pd']
#yTest = test['pd']

#print(xTrain_encode[:10],xTest_encode[:10],yTrain[:10],yTest[:10])
print(len(xTrain_encode),len(xTest_encode),len(yTrain),len(yTest))

1906673 476669 1906673 476669


In [29]:
print(xTest_encode[:10])

[[10, 35, 45], [5, 35, 40], [19, 34, 53], [5, 15, 20], [24, 7, 31], [12, 5, 17], [10, 8, 18], [21, 29, 50], [1, 8, 9], [15, 3, 18]]


In [31]:
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(xTrain_encode,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=xTest_encode,y=yTest))
err = reg.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

[-16741.2289391  -16741.22893883  16741.22893886] 0.0006161253478340928
-6.152090075151051e-07
0.0015946901937174316


In [33]:
from sklearn.linear_model import Ridge
clf1 = Ridge(alpha=1)
clf1.fit(xTrain_encode,yTrain)
print(clf1.coef_,clf1.intercept_)

print(clf1.score(X=xTest_encode,y=yTest))
err1 = clf1.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[-1.55348425e-07  9.49454494e-08 -6.04026106e-08] 0.0006158877615807608
-6.982745530681456e-07
0.0015946902599492951


In [37]:
from sklearn.linear_model import Ridge
clf2 = Ridge(alpha=10000000000000000000000)
clf2.fit(xTrain_encode,yTrain)
print(clf2.coef_,clf1.intercept_)

print(clf2.score(X=xTest_encode,y=yTest))
err2 = clf2.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[-1.97039674e-21  6.73275876e-22 -1.29712086e-21] 0.0006158877615807608
-1.947600172025332e-06
0.0015946902599492951


## Normalization(error increased)

In [9]:
from sklearn.preprocessing import normalize
#xTrain_norm = []
#train['norm_t'] = normalize(train['t'])
#train['norm_t'] = normalize(np.array(train['t']).reshape(-1, 1))
#train['norm_v'] = normalize(np.array(train['v']).reshape(-1, 1))

#for i in train.index:
#    d = []
#    t = train._get_value(i, 'norm_t')
#    d.append(train._get_value(i, 'norm_t'))
#    d.append(train._get_value(i,'norm_v'))
#    xTrain_norm.append(d)


xTrain_norm = normalize(xTrain)

#xTest_norm = []
#test['norm_t'] = normalize(np.array(test['t']).reshape(-1, 1))
#test['norm_v'] = normalize(np.array(test['v']).reshape(-1, 1))
#for i in test.index:
#    d = []
#    d.append(test._get_value(i, 'norm_t'))
#    d.append(test._get_value(i, 'norm_v'))
#    xTest_norm.append(d)

xTest_norm = normalize(xTest)


#yTrain = train['x4']
#yTest = test['x4']

print(len(xTrain_norm),len(xTest_norm),len(yTrain),len(yTest))

1906673 476669 1906673 476669


In [11]:
from sklearn import linear_model
reg1=linear_model.LinearRegression(fit_intercept=True)
reg1.fit(xTrain_norm,yTrain)
print(reg1.coef_,reg.intercept_)

[-0.90711205 -1.41989472] 1.0654107265614592


In [19]:
reg1.score(X=xTest_norm,y=yTest)

0.1389120973227025

In [21]:
err = reg1.predict(xTest_norm)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.41438709536191176


# OLS

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pandas as pd

In [15]:
data = pd.read_csv('simDTS.csv')
#data = pd.read_csv('src/visualization/simDTS.csv')

In [16]:
from sklearn import model_selection
train, test = model_selection.train_test_split(data, test_size=0.2) 
nSample = len(train.index)
x=sm.add_constant(train['v'])
est=sm.OLS(train['x4'],train['v'])
model=est.fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                     x4   R-squared (uncentered):                   0.002
Model:                            OLS   Adj. R-squared (uncentered):              0.002
Method:                 Least Squares   F-statistic:                              3109.
Date:                Wed, 02 Nov 2022   Prob (F-statistic):                        0.00
Time:                        11:49:16   Log-Likelihood:                     -1.3341e+06
No. Observations:             1906673   AIC:                                  2.668e+06
Df Residuals:                 1906672   BIC:                                  2.668e+06
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [17]:
#model.rsquared

0.0016281051708977312

In [18]:
err = model.predict(test['v'])-test['x4']
#print(err)
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.48669984966556623
