# Linear Regression

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('simDTS.csv')
new_data = data.groupby(['t']).agg(number = ('t','count'),dr=('y','sum'),edr=('pd','sum'),std = ('pd','std'))
data["dr"] = new_data["dr"]/new_data["number"]
data['c'] = data['v'] + data['t']
#data = pd.read_csv('src/visualization/simDTS.csv')

In [3]:
data

Unnamed: 0     key   t  v   x1  x2        h1        x4  del  y  \
0                 1       1   1  2  619   0 -0.100923 -0.031003    0  0   
1            100001       1   2  2  619   0  0.498312 -0.123908    0  0   
2            200001       1   3  2  619   0 -0.733160  0.572345    0  0   
3            300001       1   4  2  619   0 -0.343541  0.529761    0  0   
4            399992       1   5  2  619   0  3.113732  0.659377    0  0   
...             ...     ...  .. ..  ...  ..       ...       ...  ... ..   
2383337     1988830  100000  20  7  651   0 -2.077314  0.096079    0  0   
2383338     2087523  100000  21  7  651   0 -1.606836  0.106994    0  0   
2383339     2186171  100000  22  7  651   0 -0.553857  0.045785    0  0   
2383340     2284777  100000  23  7  651   0 -0.380921  0.125809    0  0   
2383341     2383342  100000  24  7  651   0 -0.722160 -0.039230    0  0   

                   pd       dr   c  
0        1.381276e-09      NaN   3  
1        9.396210e-07  0.00000   4  
2        1.638122e-05  0.00000   5  
3        6.487583e-05  0.00009   6  
4        1.278584e-04  0.00034   7  
...               ...      ...  ..  
2383337  4.487481e-05      NaN  27  
2383338  4.091167e-05      NaN  28  
2383339  3.677615e-05      NaN  29  
2383340  3.252146e-05      NaN  30  
2383341  2.822985e-05      NaN  31  

[2383342 rows x 13 columns]

In [4]:
from sklearn import model_selection
#x_train, x_test = model_selection.train_test_split(xList, test_size=0.2) 
#y_train, y_test = model_selection.train_test_split(data['x4'], test_size=0.2) 
train, test = model_selection.train_test_split(data, test_size=0.2) 
#print(train)

In [5]:
#train._get_value(1126070, 't')
print(test)

         Unnamed: 0    key   t   v   x1  x2        h1        x4  del  y  \
2042413      785079  85692   8   2  560   1  3.283713  1.041043    0  0   
1015072     2326731  42615  24  17  603   0 -3.289885 -0.330212    0  0   
714393      1623151  29997  17   3  516   0  0.702222  0.649650    0  0   
760745       431921  31943   5  15  639   0  2.615998  0.649650    0  0   
1462808     2345252  61394  24  24  576   1  2.963816 -0.517702    0  0   
...             ...    ...  ..  ..  ...  ..       ...       ...  ... ..   
148853      1896241   6256  20  18  526   0 -3.894979  0.121342    0  0   
1544535     1855298  64820  19  23  523   1  0.803443 -0.126898    0  0   
715043      1820904  30024  19  29  600   0  9.462944 -0.517702    0  0   
2066514     2074400  86705  21  23  570   0  1.527064 -0.155854    0  0   
2280098     2379062  95674  24  24  675   0 -7.361362 -0.517702    0  0   

               pd  dr   c  
2042413  0.002440 NaN  10  
1015072  0.000101 NaN  41  
714393   0.0019

In [6]:

from operator import index


xTrain = []
for i in train.index:
    d = []
    d.append(train._get_value(i, 't'))
    #d.append(train['t'][i])
    d.append(train._get_value(i, 'v'))
    #d.append(train['v'][i])
    d.append(train._get_value(i, 'c'))
    xTrain.append(d)




xTest = []
for i in test.index:
    d = []
    d.append(test._get_value(i, 't'))
    #d.append(test['t'][i])
    d.append(test._get_value(i, 'v'))
    #d.append(test['v'][i])
    d.append(test._get_value(i, 'c'))
    xTest.append(d)


#yTrain = train['dr']
#yTest = test['dr']
yTrain = train['pd']
yTest = test['pd']

print(len(xTrain),len(xTest),len(yTrain),len(yTest))

1906673 476669 1906673 476669


In [7]:
xTrain[0]

[15, 34, 49]

### linear regression

In [8]:
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(xTrain,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=xTest,y=yTest))
err = reg.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

[-141041.69526259 -141041.69526409  141041.69526469] 0.0005774932995224997
4.9937700676072616e-05
0.0015706560171130108


In [9]:
print(reg.score(X=xTrain,y=yTrain))
err = reg.predict(xTrain)-yTrain
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.0001005900267115889
0.0015555344943343483


### linear regression with regularization

###### alpha=1

In [10]:
from sklearn.linear_model import Ridge
clf1 = Ridge(alpha=1)
clf1.fit(xTrain,yTrain)
print(clf1.coef_,clf1.intercept_)

print(clf1.score(X=xTest,y=yTest))
err1 = clf1.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[ 1.20750821e-06 -3.19050435e-07  8.88458787e-07] 0.000578047602315792
5.065188496000683e-05
0.0015706554562159793


###### alpha=10000

In [11]:
from sklearn.linear_model import Ridge
clf2 = Ridge(alpha=999)
clf2.fit(xTrain,yTrain)
print(clf2.coef_,clf2.intercept_)

print(clf2.score(X=xTest,y=yTest))
err2 = clf2.predict(xTest)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err2**2)))

[ 1.20749921e-06 -3.19044618e-07  8.88454596e-07] 0.0005780477374064699
5.06520742573624e-05
0.0015706554560673113


### one hot encoding

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#### integer encoding

In [13]:
'''
label_encoder = LabelEncoder()
data['t_encode'] = label_encoder.fit_transform(data['t'])
print(data['t_encode'])
data['v_encode']  = label_encoder.fit_transform(data['v'])
print(data['v_encode'])
data['c_encode']  = label_encoder.fit_transform(data['c'])
print(data['c_encode'])


onehot_encoder = OneHotEncoder(handle_unknown='ignore')
onehot_encoded = onehot_encoder.fit_transform(data['t'])
print(onehot_encoded)
'''

"\nlabel_encoder = LabelEncoder()\ndata['t_encode'] = label_encoder.fit_transform(data['t'])\nprint(data['t_encode'])\ndata['v_encode']  = label_encoder.fit_transform(data['v'])\nprint(data['v_encode'])\ndata['c_encode']  = label_encoder.fit_transform(data['c'])\nprint(data['c_encode'])\n\n\nonehot_encoder = OneHotEncoder(handle_unknown='ignore')\nonehot_encoded = onehot_encoder.fit_transform(data['t'])\nprint(onehot_encoded)\n"

In [25]:
data_simplify = data[['v','t','c','dr']]
train_encode, test_encode = model_selection.train_test_split(data_simplify, test_size=0.2) 
train_encode

v   t   c  dr
862926   11  15  26 NaN
309204   23  19  42 NaN
561884   23  16  39 NaN
2286156  24  24  48 NaN
438216    1  13  14 NaN
...      ..  ..  ..  ..
627603   25  10  35 NaN
941411   21   6  27 NaN
951724   21  16  37 NaN
74445    22  16  38 NaN
1357442  13   3  16 NaN

[1906673 rows x 4 columns]

In [32]:
# reference: https://blog.csdn.net/maymay_/article/details/80198468?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522166797260416782417051075%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=166797260416782417051075&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-2-80198468-null-null.142^v63^control,201^v3^control,213^v2^t3_esquery_v3&utm_term=pandas.get_dummies&spm=1018.2226.3001.4187
train_encode.columns = ['v','t','c','dr']
train_encode = pd.get_dummies(train_encode)
#pd.get_dummies(test_encode)
train_encode

v   t   c  dr
862926   11  15  26 NaN
309204   23  19  42 NaN
561884   23  16  39 NaN
2286156  24  24  48 NaN
438216    1  13  14 NaN
...      ..  ..  ..  ..
627603   25  10  35 NaN
941411   21   6  27 NaN
951724   21  16  37 NaN
74445    22  16  38 NaN
1357442  13   3  16 NaN

[1906673 rows x 4 columns]

In [15]:
from operator import index


xTrain_encode = []
for i in train_encode.index:
    d = []
    d.append(train_encode._get_value(i, 't'))
    #d.append(train['t'][i])
    d.append(train_encode._get_value(i, 'v'))
    #d.append(train['v'][i])
    d.append(train_encode._get_value(i, 'c'))
    xTrain_encode.append(d)




xTest_encode = []
for i in test_encode.index:
    d = []
    d.append(test_encode._get_value(i, 't'))
    #d.append(test['t'][i])
    d.append(test_encode._get_value(i, 'v'))
    #d.append(test['v'][i])
    d.append(test_encode._get_value(i, 'c'))
    xTest_encode.append(d)


#yTrain = train['dr']
#yTest = test['dr']
#same as before
#yTrain = train['pd']
#yTest = test['pd']

#print(xTrain_encode[:10],xTest_encode[:10],yTrain[:10],yTest[:10])
print(len(xTrain_encode),len(xTest_encode),len(yTrain),len(yTest))

1906673 476669 1906673 476669


In [16]:
print(xTest_encode[:10])

[[3, 17, 20], [4, 31, 35], [22, 6, 28], [20, 13, 33], [17, 8, 25], [22, 14, 36], [15, 18, 33], [8, 22, 30], [17, 4, 21], [7, 32, 39]]


In [17]:
from sklearn import linear_model
reg=linear_model.LinearRegression(fit_intercept=True)
reg.fit(xTrain_encode,yTrain)
print(reg.coef_,reg.intercept_)

print(reg.score(X=xTest_encode,y=yTest))
err = reg.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

[-278347.2694346  -278347.26943469  278347.26943452] 0.0006185636937404677
-1.966496425032105e-06
0.0015706967804394426


In [18]:
xTrain_encode

[[11, 14, 25],
 [11, 19, 30],
 [23, 27, 50],
 [4, 29, 33],
 [13, 19, 32],
 [17, 3, 20],
 [15, 26, 41],
 [1, 1, 2],
 [3, 6, 9],
 [9, 2, 11],
 [4, 1, 5],
 [13, 14, 27],
 [19, 14, 33],
 [12, 30, 42],
 [17, 29, 46],
 [14, 16, 30],
 [9, 7, 16],
 [16, 13, 29],
 [21, 9, 30],
 [22, 26, 48],
 [8, 12, 20],
 [16, 27, 43],
 [6, 21, 27],
 [22, 2, 24],
 [21, 31, 52],
 [12, 19, 31],
 [6, 32, 38],
 [23, 9, 32],
 [24, 28, 52],
 [3, 33, 36],
 [4, 20, 24],
 [1, 27, 28],
 [6, 25, 31],
 [11, 5, 16],
 [13, 25, 38],
 [5, 14, 19],
 [9, 3, 12],
 [11, 25, 36],
 [13, 25, 38],
 [10, 26, 36],
 [16, 20, 36],
 [21, 24, 45],
 [9, 11, 20],
 [14, 31, 45],
 [24, 7, 31],
 [1, 24, 25],
 [8, 25, 33],
 [20, 20, 40],
 [22, 19, 41],
 [23, 33, 56],
 [6, 30, 36],
 [16, 9, 25],
 [19, 2, 21],
 [21, 19, 40],
 [22, 29, 51],
 [3, 32, 35],
 [11, 21, 32],
 [24, 17, 41],
 [18, 30, 48],
 [18, 19, 37],
 [3, 2, 5],
 [5, 22, 27],
 [20, 28, 48],
 [11, 16, 27],
 [7, 10, 17],
 [15, 10, 25],
 [3, 27, 30],
 [24, 21, 45],
 [4, 21, 25],
 [15, 31,

In [19]:
from sklearn.linear_model import Ridge
clf1 = Ridge(alpha=1)
clf1.fit(xTrain_encode,yTrain)
print(clf1.coef_,clf1.intercept_)

print(clf1.score(X=xTest_encode,y=yTest))
err1 = clf1.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[ 3.72815020e-08 -1.23048204e-07 -8.57668402e-08] 0.0006187354171691162
-2.5041740894238274e-06
0.0015706972027028437


In [20]:
from sklearn.linear_model import Ridge
clf2 = Ridge(alpha=10000000000000000000000)
clf2.fit(xTrain_encode,yTrain)
print(clf2.coef_,clf1.intercept_)

print(clf2.score(X=xTest_encode,y=yTest))
err2 = clf2.predict(xTest_encode)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err1**2)))

[-4.42917748e-22 -4.06675110e-21 -4.50966885e-21] 0.0006187354171691162
-1.4693292671452696e-07
0.0015706972027028437


## Normalization(error increased)

In [ ]:
from sklearn.preprocessing import normalize
#xTrain_norm = []
#train['norm_t'] = normalize(train['t'])
#train['norm_t'] = normalize(np.array(train['t']).reshape(-1, 1))
#train['norm_v'] = normalize(np.array(train['v']).reshape(-1, 1))

#for i in train.index:
#    d = []
#    t = train._get_value(i, 'norm_t')
#    d.append(train._get_value(i, 'norm_t'))
#    d.append(train._get_value(i,'norm_v'))
#    xTrain_norm.append(d)


xTrain_norm = normalize(xTrain)

#xTest_norm = []
#test['norm_t'] = normalize(np.array(test['t']).reshape(-1, 1))
#test['norm_v'] = normalize(np.array(test['v']).reshape(-1, 1))
#for i in test.index:
#    d = []
#    d.append(test._get_value(i, 'norm_t'))
#    d.append(test._get_value(i, 'norm_v'))
#    xTest_norm.append(d)

xTest_norm = normalize(xTest)


#yTrain = train['x4']
#yTest = test['x4']

print(len(xTrain_norm),len(xTest_norm),len(yTrain),len(yTest))

1906673 476669 1906673 476669


In [ ]:
from sklearn import linear_model
reg1=linear_model.LinearRegression(fit_intercept=True)
reg1.fit(xTrain_norm,yTrain)
print(reg1.coef_,reg.intercept_)

[-46676.85057799 -46676.85072204  46676.8547071 ] 0.0006135906441639514


In [ ]:
reg1.score(X=xTest_norm,y=yTest)

0.005446472680148973

In [ ]:
err = reg1.predict(xTest_norm)-yTest
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.0015712283182443983


# OLS

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pandas as pd

In [ ]:
data = pd.read_csv('simDTS.csv')
#data = pd.read_csv('src/visualization/simDTS.csv')

In [ ]:
from sklearn import model_selection
train, test = model_selection.train_test_split(data, test_size=0.2) 
nSample = len(train.index)
x=sm.add_constant(train['v'])
est=sm.OLS(train['x4'],train['v'])
model=est.fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                     x4   R-squared (uncentered):                   0.002
Model:                            OLS   Adj. R-squared (uncentered):              0.002
Method:                 Least Squares   F-statistic:                              3149.
Date:                Wed, 09 Nov 2022   Prob (F-statistic):                        0.00
Time:                        12:02:11   Log-Likelihood:                     -1.3332e+06
No. Observations:             1906673   AIC:                                  2.666e+06
Df Residuals:                 1906672   BIC:                                  2.667e+06
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [ ]:
#model.rsquared

In [ ]:
err = model.predict(test['v'])-test['x4']
#print(err)
#np.mean(err)
print(np.sqrt(np.mean(err**2)))

0.4875809777799
